version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cadastrousuarios
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
